<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class FillCurrencyTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('currencies')->insertOrIgnore([
            array('iso_code' => 'CUP', 'name' => 'Cuban Peso', 'iso_number' => 192, 'alternative' => 'CUC'),
            array('iso_code' => 'HTG', 'name' => 'Gourde', 'iso_number' => 332, 'alternative' => 'USD'),
            array('iso_code' => 'LSL', 'name' => 'Loti', 'iso_number' => 426, 'alternative' => 'SAR'),
            array('iso_code' => 'NAD', 'name' => 'Namibia Dollar', 'iso_number' => 516, 'alternative' => 'SAR'),
            array('iso_code' => 'PAB', 'name' => 'Balboa', 'iso_number' => 590, 'alternative' => 'USD'),
            array('iso_code' => 'SVC', 'name' => 'El Salvador Colon', 'iso_number' => 222, 'alternative' => 'USD'),
        ]);
        DB::table('currencies')->insertOrIgnore([
            array('iso_code' => 'AED', 'name' => 'UAE Dirham', 'iso_number' => 784),
            array('iso_code' => 'AFN', 'name' => 'Afghani', 'iso_number' => 971),
            array('iso_code' => 'ALL', 'name' => 'Lek', 'iso_number' => 8),
            array('iso_code' => 'AMD', 'name' => 'Armenian Dram', 'iso_number' => 51),
            array('iso_code' => 'ANG', 'name' => 'Netherlands Antillean Guilder', 'iso_number' => 532),
            array('iso_code' => 'AOA', 'name' => 'Kwanza', 'iso_number' => 973),
            array('iso_code' => 'ARS', 'name' => 'Argentine Peso', 'iso_number' => 32),
            array('iso_code' => 'AUD', 'name' => 'Australian Dollar', 'iso_number' => 36),
            array('iso_code' => 'AWG', 'name' => 'Aruban Florin', 'iso_number' => 533),
            array('iso_code' => 'AZN', 'name' => 'Azerbaijan Manat', 'iso_number' => 944),
            array('iso_code' => 'BAM', 'name' => 'Convertible Mark', 'iso_number' => 977),
            array('iso_code' => 'BBD', 'name' => 'Barbados Dollar', 'iso_number' => 52),
            array('iso_code' => 'BDT', 'name' => 'Taka', 'iso_number' => 50),
            array('iso_code' => 'BGN', 'name' => 'Bulgarian Lev', 'iso_number' => 975),
            array('iso_code' => 'BHD', 'name' => 'Bahraini Dinar', 'iso_number' => 48),
            array('iso_code' => 'BIF', 'name' => 'Burundi Franc', 'iso_number' => 108),
            array('iso_code' => 'BMD', 'name' => 'Bermudian Dollar', 'iso_number' => 60),
            array('iso_code' => 'BND', 'name' => 'Brunei Dollar', 'iso_number' => 96),
            array('iso_code' => 'BOB', 'name' => 'Boliviano', 'iso_number' => 68),
            array('iso_code' => 'BRL', 'name' => 'Brazilian Real', 'iso_number' => 986),
            array('iso_code' => 'BSD', 'name' => 'Bahamian Dollar', 'iso_number' => 44),
            array('iso_code' => 'BTN', 'name' => 'Ngultrum', 'iso_number' => 64),
            array('iso_code' => 'BWP', 'name' => 'Pula', 'iso_number' => 72),
            array('iso_code' => 'BYN', 'name' => 'Belarusian Ruble', 'iso_number' => 933),
            array('iso_code' => 'BZD', 'name' => 'Belize Dollar', 'iso_number' => 84),
            array('iso_code' => 'CAD', 'name' => 'Canadian Dollar', 'iso_number' => 124),
            array('iso_code' => 'CDF', 'name' => 'Congolese Franc', 'iso_number' => 976),
            array('iso_code' => 'CHF', 'name' => 'Swiss Franc', 'iso_number' => 756),
            array('iso_code' => 'CLP', 'name' => 'Chilean Peso', 'iso_number' => 152),
            array('iso_code' => 'CNY', 'name' => 'Yuan Renminbi', 'iso_number' => 156),
            array('iso_code' => 'COP', 'name' => 'Colombian Peso', 'iso_number' => 170),
            array('iso_code' => 'CRC', 'name' => 'Costa Rican Colon', 'iso_number' => 188),
            array('iso_code' => 'CUC', 'name' => 'Peso Convertible', 'iso_number' => 931),
            array('iso_code' => 'CVE', 'name' => 'Cabo Verde Escudo', 'iso_number' => 132),
            array('iso_code' => 'CZK', 'name' => 'Czech Koruna', 'iso_number' => 203),
            array('iso_code' => 'DJF', 'name' => 'Djibouti Franc', 'iso_number' => 262),
            array('iso_code' => 'DKK', 'name' => 'Danish Krone', 'iso_number' => 208),
            array('iso_code' => 'DOP', 'name' => 'Dominican Peso', 'iso_number' => 214),
            array('iso_code' => 'DZD', 'name' => 'Algerian Dinar', 'iso_number' => 12),
            array('iso_code' => 'EGP', 'name' => 'Egyptian Pound', 'iso_number' => 818),
            array('iso_code' => 'ERN', 'name' => 'Nakfa', 'iso_number' => 232),
            array('iso_code' => 'ETB', 'name' => 'Ethiopian Birr', 'iso_number' => 230),
            array('iso_code' => 'EUR', 'name' => 'Euro', 'iso_number' => 978),
            array('iso_code' => 'FJD', 'name' => 'Fiji Dollar', 'iso_number' => 242),
            array('iso_code' => 'GBP', 'name' => 'Pound Sterling', 'iso_number' => 826),
            array('iso_code' => 'GEL', 'name' => 'Lari', 'iso_number' => 981),
            array('iso_code' => 'GHS', 'name' => 'Ghana Cedi', 'iso_number' => 936),
            array('iso_code' => 'GIP', 'name' => 'Gibraltar Pound', 'iso_number' => 292),
            array('iso_code' => 'GMD', 'name' => 'Dalasi', 'iso_number' => 270),
            array('iso_code' => 'GNF', 'name' => 'Guinean Franc', 'iso_number' => 324),
            array('iso_code' => 'GTQ', 'name' => 'Quetzal', 'iso_number' => 320),
            array('iso_code' => 'GYD', 'name' => 'Guyana Dollar', 'iso_number' => 328),
            array('iso_code' => 'HKD', 'name' => 'Hong Kong Dollar', 'iso_number' => 344),
            array('iso_code' => 'HNL', 'name' => 'Lempira', 'iso_number' => 340),
            array('iso_code' => 'HRK', 'name' => 'Kuna', 'iso_number' => 191),

            array('iso_code' => 'HUF', 'name' => 'Forint', 'iso_number' => 348),
            array('iso_code' => 'IDR', 'name' => 'Rupiah', 'iso_number' => 360),
            array('iso_code' => 'ILS', 'name' => 'New Israeli Sheqel', 'iso_number' => 376),
            array('iso_code' => 'INR', 'name' => 'Indian Rupee', 'iso_number' => 356),
            array('iso_code' => 'IQD', 'name' => 'Iraqi Dinar', 'iso_number' => 368),
            array('iso_code' => 'IRR', 'name' => 'Iranian Rial', 'iso_number' => 364),
            array('iso_code' => 'ISK', 'name' => 'Iceland Krona', 'iso_number' => 352),
            array('iso_code' => 'JMD', 'name' => 'Jamaican Dollar', 'iso_number' => 388),
            array('iso_code' => 'JOD', 'name' => 'Jordanian Dinar', 'iso_number' => 400),
            array('iso_code' => 'JPY', 'name' => 'Yen', 'iso_number' => 392),
            array('iso_code' => 'KES', 'name' => 'Kenyan Shilling', 'iso_number' => 404),
            array('iso_code' => 'KGS', 'name' => 'Som', 'iso_number' => 417),
            array('iso_code' => 'KHR', 'name' => 'Riel', 'iso_number' => 116),
            array('iso_code' => 'KMF', 'name' => 'Comorian Franc', 'iso_number' => 174),
            array('iso_code' => 'KPW', 'name' => 'North Korean Won', 'iso_number' => 408),
            array('iso_code' => 'KRW', 'name' => 'Won', 'iso_number' => 410),
            array('iso_code' => 'KWD', 'name' => 'Kuwaiti Dinar', 'iso_number' => 414),
            array('iso_code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'iso_number' => 136),
            array('iso_code' => 'KZT', 'name' => 'Tenge', 'iso_number' => 398),
            array('iso_code' => 'LAK', 'name' => 'Lao Kip', 'iso_number' => 418),
            array('iso_code' => 'LBP', 'name' => 'Lebanese Pound', 'iso_number' => 422),
            array('iso_code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'iso_number' => 144),
            array('iso_code' => 'LRD', 'name' => 'Liberian Dollar', 'iso_number' => 430),
            
            array('iso_code' => 'LYD', 'name' => 'Libyan Dinar', 'iso_number' => 434),
            array('iso_code' => 'MAD', 'name' => 'Moroccan Dirham', 'iso_number' => 504),
            array('iso_code' => 'MDL', 'name' => 'Moldovan Leu', 'iso_number' => 498),
            array('iso_code' => 'MGA', 'name' => 'Malagasy Ariary', 'iso_number' => 969),
            array('iso_code' => 'MKD', 'name' => 'Denar', 'iso_number' => 807),
            array('iso_code' => 'MMK', 'name' => 'Kyat', 'iso_number' => 104),
            array('iso_code' => 'MNT', 'name' => 'Tugrik', 'iso_number' => 496),
            array('iso_code' => 'MOP', 'name' => 'Pataca', 'iso_number' => 446),
            array('iso_code' => 'MRO', 'name' => 'Ouguiya', 'iso_number' => 478),
            array('iso_code' => 'MUR', 'name' => 'Mauritius Rupee', 'iso_number' => 480),
            array('iso_code' => 'MVR', 'name' => 'Rufiyaa', 'iso_number' => 462),
            array('iso_code' => 'MWK', 'name' => 'Malawi Kwacha', 'iso_number' => 454),
            array('iso_code' => 'MXN', 'name' => 'Mexican Peso', 'iso_number' => 484),
            array('iso_code' => 'MYR', 'name' => 'Malaysian Ringgit', 'iso_number' => 458),
            array('iso_code' => 'MZN', 'name' => 'Mozambique Metical', 'iso_number' => 943),
            
            array('iso_code' => 'NGN', 'name' => 'Naira', 'iso_number' => 566),
            array('iso_code' => 'NIO', 'name' => 'Cordoba Oro', 'iso_number' => 558),
            array('iso_code' => 'NOK', 'name' => 'Norwegian Krone', 'iso_number' => 578),
            array('iso_code' => 'NPR', 'name' => 'Nepalese Rupee', 'iso_number' => 524),
            array('iso_code' => 'NZD', 'name' => 'New Zealand Dollar', 'iso_number' => 554),
            array('iso_code' => 'OMR', 'name' => 'Rial Omani', 'iso_number' => 512),
            
            array('iso_code' => 'PEN', 'name' => 'Sol', 'iso_number' => 604),
            array('iso_code' => 'PGK', 'name' => 'Kina', 'iso_number' => 598),
            array('iso_code' => 'PHP', 'name' => 'Philippine Piso', 'iso_number' => 608),
            array('iso_code' => 'PKR', 'name' => 'Pakistan Rupee', 'iso_number' => 586),
            array('iso_code' => 'PLN', 'name' => 'Zloty', 'iso_number' => 985),
            array('iso_code' => 'PYG', 'name' => 'Guarani', 'iso_number' => 600),
            array('iso_code' => 'QAR', 'name' => 'Qatari Rial', 'iso_number' => 634),
            array('iso_code' => 'RON', 'name' => 'Romanian Leu', 'iso_number' => 946),
            array('iso_code' => 'RSD', 'name' => 'Serbian Dinar', 'iso_number' => 941),
            array('iso_code' => 'RUB', 'name' => 'Russian Ruble', 'iso_number' => 643),
            array('iso_code' => 'RWF', 'name' => 'Rwanda Franc', 'iso_number' => 646),
            array('iso_code' => 'SAR', 'name' => 'Saudi Riyal', 'iso_number' => 682),
            array('iso_code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'iso_number' => 90),
            array('iso_code' => 'SCR', 'name' => 'Seychelles Rupee', 'iso_number' => 690),
            array('iso_code' => 'SDG', 'name' => 'Sudanese Pound', 'iso_number' => 938),
            array('iso_code' => 'SEK', 'name' => 'Swedish Krona', 'iso_number' => 752),
            array('iso_code' => 'SGD', 'name' => 'Singapore Dollar', 'iso_number' => 702),
            array('iso_code' => 'SHP', 'name' => 'Saint Helena Pound', 'iso_number' => 654),
            array('iso_code' => 'SLL', 'name' => 'Leone', 'iso_number' => 694),
            array('iso_code' => 'SOS', 'name' => 'Somali Shilling', 'iso_number' => 706),
            array('iso_code' => 'SRD', 'name' => 'Surinam Dollar', 'iso_number' => 968),
            array('iso_code' => 'SSP', 'name' => 'South Sudanese Pound', 'iso_number' => 728),
            array('iso_code' => 'STD', 'name' => 'Dobra', 'iso_number' => 678),
            
            array('iso_code' => 'SYP', 'name' => 'Syrian Pound', 'iso_number' => 760),
            array('iso_code' => 'SZL', 'name' => 'Lilangeni', 'iso_number' => 748),
            array('iso_code' => 'THB', 'name' => 'Baht', 'iso_number' => 764),
            array('iso_code' => 'TJS', 'name' => 'Somoni', 'iso_number' => 972),
            array('iso_code' => 'TMT', 'name' => 'Turkmenistan New Manat', 'iso_number' => 934),
            array('iso_code' => 'TND', 'name' => 'Tunisian Dinar', 'iso_number' => 788),
            array('iso_code' => 'TOP', 'name' => 'Pa‚Äôanga', 'iso_number' => 776),
            array('iso_code' => 'TRY', 'name' => 'Turkish Lira', 'iso_number' => 949),
            array('iso_code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'iso_number' => 780),
            array('iso_code' => 'TZS', 'name' => 'Tanzanian Shilling', 'iso_number' => 834),
            array('iso_code' => 'UAH', 'name' => 'Hryvnia', 'iso_number' => 980),
            array('iso_code' => 'UGX', 'name' => 'Uganda Shilling', 'iso_number' => 800),
            array('iso_code' => 'USD', 'name' => 'US Dollar', 'iso_number' => 840),
            array('iso_code' => 'UYU', 'name' => 'Peso Uruguayo', 'iso_number' => 858),
            array('iso_code' => 'UZS', 'name' => 'Uzbekistan Sum', 'iso_number' => 860),
            array('iso_code' => 'VEF', 'name' => 'Bol√≠var', 'iso_number' => 937),
            array('iso_code' => 'VND', 'name' => 'Dong', 'iso_number' => 704),
            array('iso_code' => 'VUV', 'name' => 'Vatu', 'iso_number' => 548),
            array('iso_code' => 'WST', 'name' => 'Tala', 'iso_number' => 882),
            array('iso_code' => 'XAF', 'name' => 'CFA Franc BEAC', 'iso_number' => 950),
            array('iso_code' => 'XCD', 'name' => 'East Caribbean Dollar', 'iso_number' => 951),
            array('iso_code' => 'XOF', 'name' => 'CFA Franc BCEAO', 'iso_number' => 952),
            array('iso_code' => 'XPF', 'name' => 'CFP Franc', 'iso_number' => 953),
            array('iso_code' => 'XXX', 'name' => 'No universal currency', 'iso_number' => 0),
            array('iso_code' => 'YER', 'name' => 'Yemeni Rial', 'iso_number' => 886),
            array('iso_code' => 'ZAR', 'name' => 'Rand', 'iso_number' => 71),
            array('iso_code' => 'ZAR', 'name' => 'Rand', 'iso_number' => 710),
            array('iso_code' => 'ZMW', 'name' => 'Zambian Kwacha', 'iso_number' => 967),
            array('iso_code' => 'ZWL', 'name' => 'Zimbabwe Dollar', 'iso_number' => 932)
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
